#dev
spring.datasource.url=jdbc:mysql://10.128.130.234:4000/pimmpd?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai&useConfig=maxPerformance&prepStmtCacheSize=1000&prepStmtCacheSqlLimit=1000000&allowMultiQueries=false&rewriteBatchedStatements=true&sessionVariables=tidb_enable_noop_functions=1
spring.datasource.username=pimmpd_rw
spring.datasource.password=${PIMP_DBS_PWD}
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.max-lifetime=1800000
jasypt.encryptor.password=${PIMP_SEC_PWD}
logging.level.citic.famc=debug

chamc.cache.type=redis
spring.cache.type=redis
spring.session.store-type=redis
spring.data.redis.sentinel.master=pimmp
spring.data.redis.sentinel.nodes=10.128.133.82:26405,10.128.133.83:26405,10.128.133.84:26405
spring.data.redis.database=11
spring.data.redis.password=${PIMP_RDS_PWD}

chamc.security.enable=true
chamc.security.ad.url=https://sso-dev.dv.com/ChamcSSO/LoginWin.ashx
chamc.security.ad.ret-url=https://pim-dev.dv.com/%23/adLogin
chamc.security.ad.app-name=pim
chamc.security.ad.public-key=fkwKJ6hVQ9iS

#SecurityFilter
chamc.sys.security.filter.enable=true
chamc.sys.security.filter.url.enable=true
chamc.security.addtional-none-filter-urls=/js/**,/css/**,/img/**,/plugins/**,/h2-console
chamc.security.addtional-none-login-urls=/**
chamc.security.logout-success-url=https://pim-dev.dv.com/%23/login
#\u767B\u5F55\u6210\u529F\u540E\u7684\u4E3B\u754C\u9762
chamc.sys.imitate-login.ret-url=https://pim-dev.dv.com/%23/dashboard

#eureka
eureka.client.register-with-eureka=false
chamc.service.token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJwaW0iLCJpc3MiOiJkcC1zZXJ2aWNlbWd0Iiwic2VydmljZXMiOlsibWVzc2FnZWNlbnRlci1hcGkiLCJicG0tYXBpIiwicmVnaXN0cnktY2VudGVyIiwidXNlcmNlbnRlci1hcGkiXSwiZXhwIjo0MTAyMzI5NjAwLCJpYXQiOjE3NDI5NzU1NjF9.BJd6WcLVffjXsJ9KfwyHRZH1ASdSO-hped8QUJ2LUagGApNXByWOoZfU_hlSX06_TeQfSrlv8aU7pEw2q6oOaxqvcYRX4GhFKRwS7v6BShXMDk05nUGObFqOqNAhDiDqZV2Jf76Hgp-5QO14ONW11eQxzka1Hvx5wEWhcC4fKTM
eureka.client.service-url.defaultZone=http://gd-dvreg01.dv.com:8761/eureka,http://gd-dvreg02.dv.com:8761/eureka

server.servlet.session.timeout=86400000

chamc.security.clients-enable=true
chamc.security.maximum-sessions=10

chamc.current.service.address=http://localhost:8088/evaluation
chamc.sso.service.address=https://sso-dev.dv.com

#\u7763\u529Ekms\u5F85\u529E
chamc.portal.kms-url=https://pim-dev.dv.com/#/PostWorkbench/SuperviseTask/
chamc.portal.matter.kms-url=https://pim-dev.dv.com/#/PostWorkbench/SuperviseTask/MatterFlow/
chamc.portal.tPost.kms-url=https://pim-dev.dv.com/#/PostWorkbench/ReportManageFlow/
chamc.portal.tPost.new-kms-url=https://pim-dev.dv.com/#/PostWorkbench/EditReport/
chamc.portal.tPost.inspect-kms-url=https://pim-dev.dv.com/#/PostWorkbench/EditInspect/
chamc.portal.tPost.create-job=https://pim-dev.dv.com/#/PostWorkbench/EditReportManage/
chamc.portal.joinHearing.kms-url=https://pim-dev.dv.com/#/PostWorkbench/JointTask/
chamc.portal.tPost.auto.create.send=7e72f951;

