#chamc.storage.profiles.active=bak
#accesskey.bak=CB6F0CAC7EE1C75D6F3E
#secretkey.bak=mhWFVvXheA5/ivjjZ8k9UDEJQCoAAAFpfuHHXRPj
#endpoint.bak=obsbak.chamc.com.cn
#bucketname.bak=test-jsj
chamc.storage.profiles.active=dev

#chamc.storage.profiles.active=dev
accesskey.dev=CFROA3VM38EVP352XT01
secretkey.dev=fgflKevggvCP1rVmZ6ex3pXHBOlC5rWzKlVfIPXq
endpoint.dev=dxobs.dv.com/
bucketname.dev=bk-pimmp

accesskey.sim=M7JZVIYYH2WLUOS8NANA
secretkey.sim=joua6BFRDxgL8gdm4BV8Ke7YlCL6NK3ZPUKiSe8C
endpoint.sim=sxobs.chamc.com.cn
bucketname.sim=bk-ypxt-gd

accesskey.prod=D08B0C9990B00FEF7B54
secretkey.prod=m9ouO1N9Q+709cjuUo6lT/2ljNwAAAFukLAP70qz
endpoint.prod=xobs.chamc.com.cn
bucketname.prod=bk-zgsypxt

connection.pool.size.prod=200
connection.pool.size=200

